// src/pages/finance/FinancePage.tsx
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Plus, Edit2, Trash2, Search, ArrowDownToLine, ArrowUpFromLine } from 'lucide-react'
import { financeApi } from '@/api/finance'
import AddIncomeModal from './AddIncomeModal'
import AddExpenseModal from './AddExpenseModal'
import { cn } from '@/lib/utils'

type Tab = 'income' | 'expense'

function fmtDate(d?: string | null) {
  if (!d) return '—'
  const [y, m, day] = d.slice(0, 10).split('-')
  return `${m}/${day}/${y}`
}

interface Props { defaultTab?: Tab }

export default function FinancePage({ defaultTab = 'income' }: Props) {
  const qc = useQueryClient()
  const [tab, setTab] = useState<Tab>(defaultTab)
  const [search, setSearch] = useState('')
  const [incomeModal,  setIncomeModal]  = useState<{ open: boolean; income?:  any }>({ open: false })
  const [expenseModal, setExpenseModal] = useState<{ open: boolean; expense?: any }>({ open: false })

  const { data: incomesData, isLoading: incomesLoading } = useQuery({
    queryKey: ['incomes', search],
    queryFn:  () => financeApi.listIncomes({ search }).then(r => r.data),
    enabled:  tab === 'income',
  })
  const incomes: any[] = incomesData?.data ?? []

  const { data: expensesData, isLoading: expensesLoading } = useQuery({
    queryKey: ['expenses', search],
    queryFn:  () => financeApi.listExpenses({ search }).then(r => r.data),
    enabled:  tab === 'expense',
  })
  const expenses: any[] = expensesData?.data ?? []

  const delIncome  = useMutation({ mutationFn: (id: number) => financeApi.deleteIncome(id),  onSuccess: () => qc.invalidateQueries({ queryKey: ['incomes'] }) })
  const delExpense = useMutation({ mutationFn: (id: number) => financeApi.deleteExpense(id), onSuccess: () => qc.invalidateQueries({ queryKey: ['expenses'] }) })

  return (
    <div className="p-6 space-y-5">
      <div className="border-b border-gray-200">
        <div className="flex">
          {[
            { id: 'income',  label: 'Income List',  icon: ArrowDownToLine },
            { id: 'expense', label: 'Expense List', icon: ArrowUpFromLine },
          ].map(t => {
            const Icon = t.icon
            return (
              <button key={t.id} onClick={() => { setTab(t.id as Tab); setSearch('') }}
                className={cn('flex items-center gap-1.5 px-4 py-2.5 text-sm border-b-2 -mb-px',
                  tab === t.id ? 'border-emerald-600 text-emerald-700 font-medium' : 'border-transparent text-gray-500 hover:text-gray-700'
                )}><Icon size={13}/>{t.label}</button>
            )
          })}
        </div>
      </div>

      <div className="card p-0 overflow-hidden">
        <div className="flex items-center justify-between px-4 py-3 border-b border-gray-100">
          <h2 className="text-base font-semibold text-gray-800">{tab === 'income' ? 'Income List' : 'Expense List'}</h2>
          {tab === 'income' ? (
            <button onClick={() => setIncomeModal({ open: true })} className="btn btn-primary flex items-center gap-1.5">
              <Plus size={14}/> Add Income
            </button>
          ) : (
            <button onClick={() => setExpenseModal({ open: true })} className="btn btn-primary flex items-center gap-1.5">
              <Plus size={14}/> Add Expense
            </button>
          )}
        </div>
        <div className="flex items-center gap-3 p-3 border-b border-gray-100">
          <div className="relative flex-1 max-w-xs">
            <Search size={14} className="absolute left-2.5 top-2.5 text-gray-400" />
            <input className="input pl-8 h-9 text-sm" placeholder="Search..." value={search} onChange={e => setSearch(e.target.value)} />
          </div>
        </div>

        {tab === 'income' && (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50/50">
                  {['Name','Invoice Number','Date','Description','Income Head','Generated By','Amount (₹)'].map(h => (
                    <th key={h} className="px-4 py-3 text-left text-xs font-medium text-gray-500 whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {incomesLoading ? <tr><td colSpan={7} className="px-4 py-8 text-center text-gray-400">Loading…</td></tr>
                : incomes.length === 0 ? <tr><td colSpan={7} className="px-4 py-8 text-center text-gray-400">No income records</td></tr>
                : incomes.map(i => (
                  <tr key={i.id} className="hover:bg-gray-50/50">
                    <td className="px-4 py-3 text-emerald-600 font-medium">
                      {i.name}
                      <div className="inline-flex gap-1 ml-2">
                        <button className="icon-btn" onClick={() => setIncomeModal({ open: true, income: i })}><Edit2 size={11}/></button>
                        <button className="icon-btn text-red-400" onClick={() => confirm('Delete?') && delIncome.mutate(i.id)}><Trash2 size={11}/></button>
                      </div>
                    </td>
                    <td className="px-4 py-3">{i.invoice_number || '—'}</td>
                    <td className="px-4 py-3 text-gray-500">{fmtDate(i.date)}</td>
                    <td className="px-4 py-3 text-gray-700 max-w-md">{i.description || '—'}</td>
                    <td className="px-4 py-3 text-emerald-600">{i.income_head_name || '—'}</td>
                    <td className="px-4 py-3 text-emerald-600">{i.generated_by_name || '—'}</td>
                    <td className="px-4 py-3 text-right font-medium">{Number(i.amount || 0).toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {tab === 'expense' && (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50/50">
                  {['Name','Invoice Number','Date','Description','Expense Head','Generated By','Amount (₹)'].map(h => (
                    <th key={h} className="px-4 py-3 text-left text-xs font-medium text-gray-500 whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {expensesLoading ? <tr><td colSpan={7} className="px-4 py-8 text-center text-gray-400">Loading…</td></tr>
                : expenses.length === 0 ? <tr><td colSpan={7} className="px-4 py-8 text-center text-gray-400">No expense records</td></tr>
                : expenses.map(e => (
                  <tr key={e.id} className="hover:bg-gray-50/50">
                    <td className="px-4 py-3 text-emerald-600 font-medium">
                      {e.name}
                      <div className="inline-flex gap-1 ml-2">
                        <button className="icon-btn" onClick={() => setExpenseModal({ open: true, expense: e })}><Edit2 size={11}/></button>
                        <button className="icon-btn text-red-400" onClick={() => confirm('Delete?') && delExpense.mutate(e.id)}><Trash2 size={11}/></button>
                      </div>
                    </td>
                    <td className="px-4 py-3">{e.invoice_number || '—'}</td>
                    <td className="px-4 py-3 text-gray-500">{fmtDate(e.date)}</td>
                    <td className="px-4 py-3 text-gray-700 max-w-md">{e.description || '—'}</td>
                    <td className="px-4 py-3 text-emerald-600">{e.expense_head_name || '—'}</td>
                    <td className="px-4 py-3 text-emerald-600">{e.generated_by_name || '—'}</td>
                    <td className="px-4 py-3 text-right font-medium">{Number(e.amount || 0).toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <AddIncomeModal
        open={incomeModal.open} income={incomeModal.income}
        onClose={() => setIncomeModal({ open: false })}
        onSuccess={() => { setIncomeModal({ open: false }); qc.invalidateQueries({ queryKey: ['incomes'] }) }}
      />
      <AddExpenseModal
        open={expenseModal.open} expense={expenseModal.expense}
        onClose={() => setExpenseModal({ open: false })}
        onSuccess={() => { setExpenseModal({ open: false }); qc.invalidateQueries({ queryKey: ['expenses'] }) }}
      />
    </div>
  )
}
