// src/pages/ambulance/AmbulancePage.tsx
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Search, Plus, Edit2, Trash2, Truck, Eye, Printer } from 'lucide-react'
import { ambulanceApi } from '@/api/ambulance'
import AddAmbulanceModal from './AddAmbulanceModal'
import AddAmbulanceCallModal from './AddAmbulanceCallModal'
import { cn } from '@/lib/utils'

type Tab = 'calls' | 'vehicles'

export default function AmbulancePage() {
  const qc = useQueryClient()
  const [tab, setTab] = useState<Tab>('calls')
  const [search, setSearch] = useState('')
  const [callModal, setCallModal] = useState(false)
  const [vehModal, setVehModal]   = useState<{ open: boolean; vehicle?: any }>({ open: false })

  const { data: callsData, isLoading: callsLoading } = useQuery({
    queryKey: ['amb-calls', search],
    queryFn:  () => ambulanceApi.listBills({ search }).then(r => r.data),
    enabled:  tab === 'calls',
  })

  const { data: vehData, isLoading: vehLoading } = useQuery({
    queryKey: ['amb-vehicles', search],
    queryFn:  () => ambulanceApi.listVehicles({ search }).then(r => r.data),
    enabled:  tab === 'vehicles',
  })

  const calls: any[]    = callsData?.data ?? []
  const vehicles: any[] = vehData?.data ?? []

  const delVeh = useMutation({
    mutationFn: (id: number) => ambulanceApi.deleteVehicle(id),
    onSuccess:  () => qc.invalidateQueries({ queryKey: ['amb-vehicles'] }),
  })

  return (
    <div className="p-6 space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-gray-900">Ambulance</h1>
          <p className="text-sm text-gray-500 mt-0.5">Call records and fleet management</p>
        </div>
        <div className="flex gap-2">
          <button onClick={() => setTab('vehicles')} className="btn btn-outline flex items-center gap-1.5">
            <Truck size={14}/> Ambulance List
          </button>
          <button onClick={() => setCallModal(true)} className="btn btn-primary flex items-center gap-1.5">
            <Plus size={14}/> Add Ambulance Call
          </button>
        </div>
      </div>

      <div className="border-b border-gray-200">
        <div className="flex">
          {[
            { id: 'calls',    label: 'Ambulance Call List' },
            { id: 'vehicles', label: 'Ambulance List' },
          ].map(t => (
            <button key={t.id} onClick={() => setTab(t.id as Tab)}
              className={cn('px-4 py-2.5 text-sm border-b-2 -mb-px',
                tab === t.id ? 'border-emerald-600 text-emerald-700 font-medium' : 'border-transparent text-gray-500 hover:text-gray-700'
              )}>{t.label}</button>
          ))}
        </div>
      </div>

      {tab === 'calls' && (
        <div className="card overflow-hidden p-0">
          <div className="flex items-center gap-3 p-3 border-b border-gray-100">
            <div className="relative flex-1 max-w-xs">
              <Search size={14} className="absolute left-2.5 top-2.5 text-gray-400" />
              <input className="input pl-8 h-9 text-sm" placeholder="Search calls..." value={search} onChange={e => setSearch(e.target.value)} />
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50/50">
                  {['Bill No','Case ID','Patient Name','Generated By','Vehicle Number','Vehicle Model','Driver Name','Driver Contact No','Patient Address','Date','Amount (₹)','Discount (%)','Tax (%)','Net Amount (₹)','Paid (₹)','Balance (₹)','Action'].map(h => (
                    <th key={h} className="px-3 py-3 text-left text-xs font-medium text-gray-500 whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {callsLoading ? <tr><td colSpan={17} className="px-4 py-8 text-center text-gray-400">Loading…</td></tr>
                : calls.length === 0 ? <tr><td colSpan={17} className="px-4 py-8 text-center text-gray-400">No calls</td></tr>
                : calls.map(c => (
                  <tr key={c.id} className="hover:bg-gray-50/50">
                    <td className="px-3 py-3 text-emerald-600 text-xs font-medium">{c.bill_no}</td>
                    <td className="px-3 py-3 text-xs text-gray-500">{c.case_id || '—'}</td>
                    <td className="px-3 py-3 text-xs">{c.patient_name || (c.patient_id ? `#${c.patient_id}` : '—')}</td>
                    <td className="px-3 py-3 text-xs text-gray-500">{c.generated_by_name || '—'}</td>
                    <td className="px-3 py-3 text-xs">{c.vehicle_no || '—'}</td>
                    <td className="px-3 py-3 text-xs">{c.vehicle_model || '—'}</td>
                    <td className="px-3 py-3 text-xs">{c.driver_name || '—'}</td>
                    <td className="px-3 py-3 text-xs">{c.driver_contact || '—'}</td>
                    <td className="px-3 py-3 text-xs text-gray-500 truncate max-w-[160px]">{c.patient_address || '—'}</td>
                    <td className="px-3 py-3 text-xs text-gray-500">{c.call_date ? new Date(c.call_date).toLocaleString() : (c.created_at ? new Date(c.created_at).toLocaleString() : '—')}</td>
                    <td className="px-3 py-3 text-xs">₹{Number(c.amount || 0).toFixed(2)}</td>
                    <td className="px-3 py-3 text-xs text-gray-500">₹{Number(c.discount || 0).toFixed(2)} ({Number(c.discount_percent || 0).toFixed(0)} %)</td>
                    <td className="px-3 py-3 text-xs text-gray-500">₹{Number(c.tax_amount || 0).toFixed(2)} ({Number(c.tax_percent || 0).toFixed(0)} %)</td>
                    <td className="px-3 py-3 text-xs font-medium">₹{Number(c.net_amount || 0).toFixed(2)}</td>
                    <td className="px-3 py-3 text-xs text-emerald-600">₹{Number(c.paid || 0).toFixed(2)}</td>
                    <td className="px-3 py-3 text-xs">
                      {Number(c.balance || 0) > 0
                        ? <span className="text-red-500 font-medium">₹{Number(c.balance).toFixed(2)}</span>
                        : <span className="text-emerald-500">₹0.00</span>}
                    </td>
                    <td className="px-3 py-3">
                      <div className="flex gap-1">
                        <button className="icon-btn" title="Print"><Printer size={11}/></button>
                        <button className="icon-btn" title="View"><Eye size={11}/></button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {tab === 'vehicles' && (
        <div className="card overflow-hidden p-0">
          <div className="flex items-center gap-3 p-3 border-b border-gray-100">
            <div className="relative flex-1 max-w-xs">
              <Search size={14} className="absolute left-2.5 top-2.5 text-gray-400" />
              <input className="input pl-8 h-9 text-sm" placeholder="Search vehicles..." value={search} onChange={e => setSearch(e.target.value)} />
            </div>
            <div className="flex-1" />
            <button onClick={() => setVehModal({ open: true })} className="btn btn-primary text-sm flex items-center gap-1.5">
              <Plus size={13}/> Add Ambulance
            </button>
          </div>
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-100 bg-gray-50/50">
                {['Vehicle Number','Vehicle Model','Year Made','Driver Name','Driver License','Driver Contact','Note','Vehicle Type','Action'].map(h => (
                  <th key={h} className="px-4 py-3 text-left text-xs font-medium text-gray-500">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {vehLoading ? <tr><td colSpan={9} className="px-4 py-8 text-center text-gray-400">Loading…</td></tr>
              : vehicles.length === 0 ? <tr><td colSpan={9} className="px-4 py-8 text-center text-gray-400">No vehicles</td></tr>
              : vehicles.map(v => (
                <tr key={v.id} className="hover:bg-gray-50/50">
                  <td className="px-4 py-3 text-emerald-600 font-medium">{v.vehicle_no}</td>
                  <td className="px-4 py-3">{v.model || '—'}</td>
                  <td className="px-4 py-3 text-gray-500">{v.year_made || '—'}</td>
                  <td className="px-4 py-3 text-gray-500">{v.driver_name || '—'}</td>
                  <td className="px-4 py-3 text-gray-500">{v.driver_license || '—'}</td>
                  <td className="px-4 py-3 text-gray-500">{v.driver_contact || '—'}</td>
                  <td className="px-4 py-3 text-gray-500 truncate max-w-xs">{v.note || '—'}</td>
                  <td className="px-4 py-3"><span className="badge badge-blue">{v.vehicle_type || '—'}</span></td>
                  <td className="px-4 py-3">
                    <div className="flex gap-1">
                      <button className="icon-btn" onClick={() => setVehModal({ open: true, vehicle: v })}><Edit2 size={12}/></button>
                      <button className="icon-btn text-red-400" onClick={() => confirm(`Delete ${v.vehicle_no}?`) && delVeh.mutate(v.id)}><Trash2 size={12}/></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <AddAmbulanceCallModal
        open={callModal}
        onClose={() => setCallModal(false)}
        onSuccess={() => { setCallModal(false); qc.invalidateQueries({ queryKey: ['amb-calls'] }) }}
      />
      <AddAmbulanceModal
        open={vehModal.open}
        vehicle={vehModal.vehicle}
        onClose={() => setVehModal({ open: false })}
        onSuccess={() => { setVehModal({ open: false }); qc.invalidateQueries({ queryKey: ['amb-vehicles'] }) }}
      />
    </div>
  )
}
