// src/pages/birth_death/BirthDeathPage.tsx
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Search, Plus, Edit2, Trash2, Baby, Cross } from 'lucide-react'
import { birthDeathApi } from '@/api/birth_death'
import AddBirthRecordModal from './AddBirthRecordModal'
import AddDeathRecordModal from './AddDeathRecordModal'
import { cn } from '@/lib/utils'

type Tab = 'birth' | 'death'

export default function BirthDeathPage() {
  const qc = useQueryClient()
  const [tab, setTab]       = useState<Tab>('birth')
  const [search, setSearch] = useState('')
  const [birthModal, setBirthModal] = useState<{ open: boolean; record?: any }>({ open: false })
  const [deathModal, setDeathModal] = useState<{ open: boolean; record?: any }>({ open: false })

  const { data: birthData, isLoading: birthLoading } = useQuery({
    queryKey: ['bd-births', search],
    queryFn:  () => birthDeathApi.listBirths({ search }).then(r => r.data),
    enabled:  tab === 'birth',
  })

  const { data: deathData, isLoading: deathLoading } = useQuery({
    queryKey: ['bd-deaths', search],
    queryFn:  () => birthDeathApi.listDeaths({ search }).then(r => r.data),
    enabled:  tab === 'death',
  })

  const births: any[] = birthData?.data ?? []
  const deaths: any[] = deathData?.data ?? []

  const delBirth = useMutation({ mutationFn: (id: number) => birthDeathApi.deleteBirth(id), onSuccess: () => qc.invalidateQueries({ queryKey: ['bd-births'] }) })
  const delDeath = useMutation({ mutationFn: (id: number) => birthDeathApi.deleteDeath(id), onSuccess: () => qc.invalidateQueries({ queryKey: ['bd-deaths'] }) })

  return (
    <div className="p-6 space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-gray-900">Birth &amp; Death Record</h1>
          <p className="text-sm text-gray-500 mt-0.5">Track births and deaths</p>
        </div>
        <div>
          {tab === 'birth' ? (
            <button onClick={() => setBirthModal({ open: true })} className="btn btn-primary flex items-center gap-1.5">
              <Plus size={14}/> Add Birth Record
            </button>
          ) : (
            <button onClick={() => setDeathModal({ open: true })} className="btn btn-primary flex items-center gap-1.5">
              <Plus size={14}/> Add Death Record
            </button>
          )}
        </div>
      </div>

      <div className="border-b border-gray-200">
        <div className="flex">
          {[
            { id: 'birth', label: 'Birth Record', icon: Baby },
            { id: 'death', label: 'Death Record', icon: Cross },
          ].map(t => {
            const Icon = t.icon
            return (
              <button key={t.id} onClick={() => { setTab(t.id as Tab); setSearch('') }}
                className={cn('flex items-center gap-1.5 px-4 py-2.5 text-sm border-b-2 -mb-px',
                  tab === t.id ? 'border-emerald-600 text-emerald-700 font-medium' : 'border-transparent text-gray-500 hover:text-gray-700'
                )}><Icon size={13}/>{t.label}</button>
            )
          })}
        </div>
      </div>

      <div className="card overflow-hidden p-0">
        <div className="flex items-center gap-3 p-3 border-b border-gray-100">
          <div className="relative flex-1 max-w-xs">
            <Search size={14} className="absolute left-2.5 top-2.5 text-gray-400" />
            <input className="input pl-8 h-9 text-sm" placeholder="Search..." value={search} onChange={e => setSearch(e.target.value)} />
          </div>
        </div>

        {tab === 'birth' && (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50/50">
                  {['Reference No','Case ID','Generated By','Child Name','Gender','Birth Date','Mother Name','Father Name','Report','Action'].map(h => (
                    <th key={h} className="px-4 py-3 text-left text-xs font-medium text-gray-500 whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {birthLoading ? <tr><td colSpan={10} className="px-4 py-8 text-center text-gray-400">Loading…</td></tr>
                : births.length === 0 ? <tr><td colSpan={10} className="px-4 py-8 text-center text-gray-400">No birth records</td></tr>
                : births.map(b => (
                  <tr key={b.id} className="hover:bg-gray-50/50">
                    <td className="px-4 py-3 text-emerald-600 font-medium text-xs">{b.reference_no}</td>
                    <td className="px-4 py-3 text-xs">{b.case_id ?? '—'}</td>
                    <td className="px-4 py-3 text-xs text-gray-500">{b.generated_by_name || '—'}</td>
                    <td className="px-4 py-3 text-xs">{b.child_name || '—'}</td>
                    <td className="px-4 py-3 text-xs">{b.gender}</td>
                    <td className="px-4 py-3 text-xs text-gray-500">{b.birth_date ? new Date(b.birth_date).toLocaleString() : '—'}</td>
                    <td className="px-4 py-3 text-xs text-emerald-600">{b.mother_name || '—'}</td>
                    <td className="px-4 py-3 text-xs">{b.father_name || '—'}</td>
                    <td className="px-4 py-3 text-xs text-gray-500">{b.report || '—'}</td>
                    <td className="px-4 py-3">
                      <div className="flex gap-1">
                        <button className="icon-btn" onClick={() => setBirthModal({ open: true, record: b })}><Edit2 size={12}/></button>
                        <button className="icon-btn text-red-400" onClick={() => confirm('Delete?') && delBirth.mutate(b.id)}><Trash2 size={12}/></button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {tab === 'death' && (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50/50">
                  {['Reference No','Case ID','Generated By','Patient Name','Guardian Name','Gender','Death Date','Report','Action'].map(h => (
                    <th key={h} className="px-4 py-3 text-left text-xs font-medium text-gray-500 whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {deathLoading ? <tr><td colSpan={9} className="px-4 py-8 text-center text-gray-400">Loading…</td></tr>
                : deaths.length === 0 ? <tr><td colSpan={9} className="px-4 py-8 text-center text-gray-400">No death records</td></tr>
                : deaths.map(d => (
                  <tr key={d.id} className="hover:bg-gray-50/50">
                    <td className="px-4 py-3 text-emerald-600 font-medium text-xs">{d.reference_no}</td>
                    <td className="px-4 py-3 text-xs">{d.case_id ?? '—'}</td>
                    <td className="px-4 py-3 text-xs text-gray-500">{d.generated_by_name || '—'}</td>
                    <td className="px-4 py-3 text-xs text-emerald-600">{d.patient_name || '—'}</td>
                    <td className="px-4 py-3 text-xs">{d.guardian_name || '—'}</td>
                    <td className="px-4 py-3 text-xs">{d.gender || '—'}</td>
                    <td className="px-4 py-3 text-xs text-gray-500">{d.death_date ? new Date(d.death_date).toLocaleString() : '—'}</td>
                    <td className="px-4 py-3 text-xs text-gray-500">{d.report || '—'}</td>
                    <td className="px-4 py-3">
                      <div className="flex gap-1">
                        <button className="icon-btn" onClick={() => setDeathModal({ open: true, record: d })}><Edit2 size={12}/></button>
                        <button className="icon-btn text-red-400" onClick={() => confirm('Delete?') && delDeath.mutate(d.id)}><Trash2 size={12}/></button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <AddBirthRecordModal
        open={birthModal.open} record={birthModal.record}
        onClose={() => setBirthModal({ open: false })}
        onSuccess={() => { setBirthModal({ open: false }); qc.invalidateQueries({ queryKey: ['bd-births'] }) }}
      />
      <AddDeathRecordModal
        open={deathModal.open} record={deathModal.record}
        onClose={() => setDeathModal({ open: false })}
        onSuccess={() => { setDeathModal({ open: false }); qc.invalidateQueries({ queryKey: ['bd-deaths'] }) }}
      />
    </div>
  )
}
